# Generated by Django 4.0.3 on 2022-10-27 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salesrecord',
            old_name='vin',
            new_name='automobile',
        ),
    ]
