# Generated by Django 4.0.3 on 2022-10-27 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='reason',
            field=models.TextField(null=True),
        ),
    ]
