# Generated by Django 4.0.3 on 2022-11-02 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0002_service_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='canceled',
            field=models.BooleanField(default=False),
        ),
    ]
